version: 0.2

phases:
  install:
    commands:
      - echo "test"
  pre_build:
    commands:
      - sudo yum update
  build:
    commands:
      - echo "Hello, World! (phase=build)"
      - ls -al /home/vagrant
